[General]
LoadColor=#fffbeb
Name=Alucard

[Background]
Type=0
Color=#fffbeb
ImageFile=

[Foreground]
Color=#fffbeb
Opacity=0
Width=700
Margin=65
Padding=10
Position=1
Rounding=0
RoundingDisabled=10

[ForegroundBlur]
Enabled=false
Radius=32

[ForegroundShadow]
Enabled=false
Color=#000000
Radius=8
Offset=2

[Text]
Color=#1f1f1f
Font="Courier New,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
Misspelled=#6c664b

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48
