[General]
LoadColor=#282a36
Name=Dracula

[Background]
Type=0
Color=#282a36
ImageFile=

[Foreground]
Color=#282a36
Opacity=0
Width=700
Margin=65
Padding=10
Position=1
Rounding=0
RoundingDisabled=10

[ForegroundBlur]
Enabled=false
Radius=32

[ForegroundShadow]
Enabled=false
Color=#000000
Radius=8
Offset=2

[Text]
Color=#f8f8f2
Font="Courier New,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
Misspelled=#6272a4

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48
